version: '3.8'

services:
  db:
    image: postgres:13
    container_name: bakery-system-db
    environment:
      POSTGRES_DB: bakery_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  redis:
    image: redis:alpine
    container_name: bakery-system-redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  rabbitmq:
    image: rabbitmq:3-management
    container_name: bakery-system-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "status"]
      interval: 10s
      timeout: 10s
      retries: 5
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  backend:
    build:
      context: ./backend
    container_name: bakery-system-backend
    ports:
      - "5000:5000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_NAME: bakery_db
      DB_USER: postgres
      DB_PASSWORD: yourpassword
      REDIS_URL: redis://redis:6379/0
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

  worker:
    build:
      context: ./worker
    container_name: bakery-system-worker
    depends_on:
      backend:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    environment:
      DATABASE_URL: postgresql://postgres:yourpassword@db:5432/bakery_db
      REDIS_URL: redis://redis:6379/0
      RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672/
    networks:
      - bakery-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  frontend:
    build:
      context: ./frontend
    container_name: bakery-system-frontend
    ports:
      - "3000:3000"
    depends_on:
      backend:
        condition: service_started
    networks:
      - bakery-network
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 300M

volumes:
  db_data:

networks:
  bakery-network:
    driver: bridge
